### PR TITLE
Use WindowOrWorkerGlobalScope as a mixin

### PR DESCRIPTION
**Pull request by foolip**
https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope-mixin

***
<a href="https://pr-preview.s3.amazonaws.com/foolip/webappsec-secure-contexts/pull/64.html" title="Last updated on Feb 9, 2019, 12:10 AM UTC (6df216b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-secure-contexts/64/5aafba0...foolip:6df216b.html" title="Last updated on Feb 9, 2019, 12:10 AM UTC (6df216b)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I was thinking of merging this, but it seems each previous commit also contains the generated HTML.

**Comment by foolip** [comment]
I presumed that was done by the maintainers, since otherwise the diff will flip flop back and forth depending on what Bikeshed version people have installed.

**Comment by mikewest** [comment]
:+1:, thanks @foolip.

**Comment by foolip** [comment]
@mikewest I hadn't updated the generated output, will you push a separate commit to do that?

**Pull request merged**
