### PR TITLE
Fix typo "it’s creator"

### PR DESCRIPTION
**Pull request by fred-wang**
***
<a href="https://pr-preview.s3.amazonaws.com/fred-wang/webappsec-secure-contexts/pull/87.html" title="Last updated on Apr 21, 2021, 12:04 PM UTC (b51a282)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-secure-contexts/87/b9d7e99...fred-wang:b51a282.html" title="Last updated on Apr 21, 2021, 12:04 PM UTC (b51a282)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
You need to modify index.src.html too.

**Comment by fred-wang** [comment]
Thanks, for some reason it uses a different apostrophe

**Comment by annevk** [comment]
Bikeshed generates the fancy one.

**Comment by annevk** [comment]
(I cannot mark this as non-substantive for some reason. I can ignore the ipr bot, but not sure if I should...)

**Review by sideshowbarker — APPROVED** [review]

**Comment by fred-wang** [comment]
Thanks.

**Pull request merged**
